// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO6b5bual-GeGxO6P2KS8KWrvNZgkpNAQ',
    appId: '1:836714881485:web:0e53cce3abfd3e9820e484',
    messagingSenderId: '836714881485',
    projectId: 'fir-app-d1685',
    authDomain: 'fir-app-d1685.firebaseapp.com',
    storageBucket: 'fir-app-d1685.appspot.com',
    measurementId: 'G-D0EK0SZLST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Qs605Mqr0YqH6zTMihN0C_fA9lwd4zg',
    appId: '1:836714881485:android:5a4536c672e5ac0520e484',
    messagingSenderId: '836714881485',
    projectId: 'fir-app-d1685',
    storageBucket: 'fir-app-d1685.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN80TJVwjeK06r03lzvwbFdMMdBHhI4zg',
    appId: '1:836714881485:ios:09eb1d20e1f6be4620e484',
    messagingSenderId: '836714881485',
    projectId: 'fir-app-d1685',
    storageBucket: 'fir-app-d1685.appspot.com',
    iosBundleId: 'com.example.loginSignupFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN80TJVwjeK06r03lzvwbFdMMdBHhI4zg',
    appId: '1:836714881485:ios:40674e782d00181920e484',
    messagingSenderId: '836714881485',
    projectId: 'fir-app-d1685',
    storageBucket: 'fir-app-d1685.appspot.com',
    iosBundleId: 'com.example.loginSignupFirebase.RunnerTests',
  );
}
